services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: devcontainer.env
    depends_on:
      - db
    volumes:
      - ..:/workspace/:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d app_db -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
